services:
  redis:
    image: redis
    container_name: meter-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - redis_net
  
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meterdb
      MYSQL_USER: meter
      MYSQL_PASSWORD: meter1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mysql_net

networks:
  redis_net:
    driver: bridge
  mysql_net:
    driver: bridge
